config/routes.rb
Blog::Application.routes.draw do
	devise_for :users

	get 'posts/page/:page' => 'posts#index'
	get 'tags/:tag', to: 'posts#tagged', as: :tag
	
	match 'tagged', to: 'posts#tagged', :as => 'tagged', via: 'get' 
	resources :posts

	root to: "welcome#index"
  
  	resources :posts do
  		resources :comments
  	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
  acts_as_taggable
  acts_as_taggable_on :tags
  has_attached_file :avatar, 
                    :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :default_url => "/images/style/missing_:style.png"
  validates_attachment :avatar,
                       :presence => true,
                       :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ },
                       :size => { :in => 0..1.megabytes }

  validates :title, presence: true, 
  					length: { minimum: 5 }

  validates_presence_of :tag_list  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

  protected
  def authorize_blogger!
    if user_signed_in?
      return
    else
      flash[:notice] = 'You need to sign in first'
      redirect_to new_user_session_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authorize_blogger!, only: :destroy
 
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:commenter, :body))
    redirect_to post_path(@post)
  end
 
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authorize_blogger!, :except => [:index, :show, :tagged]
  rescue_from Pundit::NotAuthorizedError, :with => :record_not_found

	def new
  		@post = Post.new
	end

	def create
      @post = Post.new(post_params)
      authorize @post
  	 	if @post.save
    		redirect_to @post
  		else
    		render 'new'
  		end
	end

	def show
  		@post = Post.find(params[:id])
  end	

	def index
    if params[:tag].present?
      @posts = Post
              .paginate(Post.tagged_with(params[:tag]), :page => params[:page], :per_page => 10)
              .order('created_at DESC')
    else
      @posts = Post
              .paginate(:page => params[:page], :per_page => 10)
              .order('created_at DESC')
    end
  end

	def edit
  		@post = Post.find(params[:id])
      authorize @post
	end

	def update
  		@post = Post.find(params[:id])
      authorize @post 
  		if @post.update(post_params)
    		redirect_to @post
  		else
    		render 'edit'
  		end
	end

	def destroy
  		@post = Post.find(params[:id])
      authorize @post
  		@post.destroy
 	    redirect_to posts_path
	end

  def tagged
    if params[:tag].present? 
      @posts = Post.tagged_with(params[:tag])
    else 
      @posts = Post.postall
    end  
  end

	private
    def post_params
      params.require(:post).permit(:title, :text, :tag_list, :avatar)
  	end

    def record_not_found
      redirect_to posts_path, :alert => "You are not authorized to do that"
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/common/_session.html.erb
<%- if user_signed_in? %>
  <p>Hello <%= current_user.email %><br />
  <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></p>
<%- else %>
  <p>
    <%= link_to 'Register', new_user_registration_path %> |
    <%= link_to 'Sign in', new_user_session_path %>
  </p>
<%- end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div id="secondaryContent">
      <%= render 'common/session' %>
  </div>
  <%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :multipart => true }  do |f| %>
  <% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.label :tags, "Tags (separated by commas)" %>
    <%= f.text_field :tag_list %>
  </p>

  <p>
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing Posts</h1>
<%= link_to 'New post', new_post_path %>
<br></br>
<%= will_paginate(@posts, :renderer => WillPaginate::ActionView::LinkRenderer)%>
<br></br>
<table>
  <tr>
    <th>Cover Image</th>
    <th>Title</th>
    <th>Text</th>
    <th>Tags</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Destroy</th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= image_tag post.avatar.url(:thumb) %></td>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
      <td><%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></td>
      <td><%= link_to 'Show', post_path(post) %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<br></br>
<%= will_paginate(@posts, :renderer => WillPaginate::ActionView::LinkRenderer)%>

app/views/posts/new.html.erb
<h1>New post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Avatar:</strong>
  <%= image_tag @post.avatar.url(:medium) %>
</p>
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<p>
	<strong>Tags:</strong>
	<% @post.tags.any? %>
  		<% @post.tags.each do |tag| %>
  		<%= link_to tag.name, tagged_url(:tag => tag.name) %>
	<% end %>
</p> 

<h2>Comments</h2>
<%= render @post.comments %>
 
<h2>Add a comment:</h2>
<%= render "comments/form" %>
 
<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %>

app/views/posts/tagged.html.erb
<h1>Listing Tags</h1>
<%= link_to 'New post', new_post_path %>
<br></br>

<br></br>
<table>
  <tr>
    <th>Cover Image</th>
    <th>Title</th>
    <th>Text</th>
    <th>Tags</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Destroy</th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= image_tag post.avatar.url(:thumb) %></td>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
      <td>Tags: <%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></td>
      <td><%= link_to 'Show', post_path(post) %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<br></br>
<%= link_to 'Back to Posts', posts_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to "My Blog", controller: "posts" %>